
#ifndef OPENAO_EXPERIMENTAL_GAME_ACCOUNT_LOGOUTCOMMAND_H
#define OPENAO_EXPERIMENTAL_GAME_ACCOUNT_LOGOUTCOMMAND_H

namespace openao::experimental::game::account {

struct LogoutCommand {

};

}

#endif// OPENAO_EXPERIMENTAL_GAME_ACCOUNT_LOGOUTCOMMAND_H
